Cap oslo.config version
The plugin CI is failing right now because python-keystoneclient
fails to import the latest oslo.config package.

Traceback (most recent call last):
  File "stacklight_tests/run_tests.py", line 75, in <module>
    import_tests()
  File "stacklight_tests/run_tests.py", line 44, in import_tests
    from stacklight_tests.elasticsearch_kibana import test_smoke_bvt  # noqa
  File "/home/jenkins/workspace/8.0.fuel-plugin.lma-collector.deploy-test/stacklight_tests/elasticsearch_kibana/test_smoke_bvt.py", line 18, in <module>
    from stacklight_tests.elasticsearch_kibana import api
  File "/home/jenkins/workspace/8.0.fuel-plugin.lma-collector.deploy-test/stacklight_tests/elasticsearch_kibana/api.py", line 19, in <module>
    from stacklight_tests import base_test
  File "/home/jenkins/workspace/8.0.fuel-plugin.lma-collector.deploy-test/stacklight_tests/base_test.py", line 19, in <module>
    from fuelweb_test.tests import base_test_case
  File "/home/jenkins/workspace/8.0.fuel-plugin.lma-collector.deploy-test/venv_test/local/lib/python2.7/site-packages/fuelweb_test/tests/base_test_case.py", line 24, in <module>
    from fuelweb_test.models.environment import EnvironmentModel
  File "/home/jenkins/workspace/8.0.fuel-plugin.lma-collector.deploy-test/venv_test/local/lib/python2.7/site-packages/fuelweb_test/models/environment.py", line 45, in <module>
    from fuelweb_test.models.fuel_web_client import FuelWebClient
  File "/home/jenkins/workspace/8.0.fuel-plugin.lma-collector.deploy-test/venv_test/local/lib/python2.7/site-packages/fuelweb_test/models/fuel_web_client.py", line 63, in <module>
    from fuelweb_test.models.nailgun_client import NailgunClient
  File "/home/jenkins/workspace/8.0.fuel-plugin.lma-collector.deploy-test/venv_test/local/lib/python2.7/site-packages/fuelweb_test/models/nailgun_client.py", line 18, in <module>
    from fuelweb_test.helpers.http import HTTPClient
  File "/home/jenkins/workspace/8.0.fuel-plugin.lma-collector.deploy-test/venv_test/local/lib/python2.7/site-packages/fuelweb_test/helpers/http.py", line 19, in <module>
    from keystoneclient.v2_0 import Client as KeystoneClient
  File "/home/jenkins/workspace/8.0.fuel-plugin.lma-collector.deploy-test/venv_test/local/lib/python2.7/site-packages/keystoneclient/v2_0/__init__.py", line 1, in <module>
    from keystoneclient.v2_0.client import Client  # noqa
  File "/home/jenkins/workspace/8.0.fuel-plugin.lma-collector.deploy-test/venv_test/local/lib/python2.7/site-packages/keystoneclient/v2_0/client.py", line 19, in <module>
    from keystoneclient.auth.identity import v2 as v2_auth
  File "/home/jenkins/workspace/8.0.fuel-plugin.lma-collector.deploy-test/venv_test/local/lib/python2.7/site-packages/keystoneclient/auth/__init__.py", line 16, in <module>
    from keystoneclient.auth.conf import *  # noqa
  File "/home/jenkins/workspace/8.0.fuel-plugin.lma-collector.deploy-test/venv_test/local/lib/python2.7/site-packages/keystoneclient/auth/conf.py", line 14, in <module>
    from oslo_config import cfg
  File "/home/jenkins/workspace/8.0.fuel-plugin.lma-collector.deploy-test/venv_test/local/lib/python2.7/site-packages/oslo_config/cfg.py", line 378, in <module>
    from oslo_config._i18n import _LI, _LW
  File "/home/jenkins/workspace/8.0.fuel-plugin.lma-collector.deploy-test/venv_test/local/lib/python2.7/site-packages/oslo_config/_i18n.py", line 32, in <module>
    _C = _translators.contextual_form
AttributeError: 'TranslatorFactory' object has no attribute 'contextual_form'

Change-Id: I2aa14aaebb908b56c6c6901d8631525bd5080c36